name: WeebProfile
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:

jobs:
  weeb_profile:
    runs-on: ubuntu-latest
    steps:
      - name: 🦀 LastFM & Github 🦀
        uses: LucasHenriqueDiniz/WeebProfile@main
        with:
          FILENAME: LastFM.svg
          GIST_ID: 8aacc3d1ccca110d8358e35517d8fe40
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          STORAGE_METHOD: gist

          PLUGIN_LASTFM: true
          PLUGIN_LASTFM_USERNAME: Amayacrab
          PLUGIN_LASTFM_SECTIONS: recent_tracks, top_artists_grid
          PLUGIN_LASTFM_RECENT_TRACKS_MAX: 5
          PLUGIN_LASTFM_TOP_ARTISTS_MAX: 4
          PLUGIN_LASTFM_TOP_ALBUMS_MAX: 4

          # Github Plugin corrections
          PLUGIN_GITHUB: true
          PLUGIN_GITHUB_USERNAME: LucasHenriqueDiniz
          PLUGIN_GITHUB_SECTIONS: favorite_languages
          PLUGIN_GITHUB_FAVORITE_LANGUAGES_TITLE: "<qnt> Languages"
          
      - name: 🦀 MyAnimeList 🦀
        uses: LucasHenriqueDiniz/WeebProfile@main
        with:
          FILENAME: MyAnimeList.svg
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          STORAGE_METHOD: gist
          SIZE: half
          STYLE: default

          PLUGIN_MYANIMELIST: true
          PLUGIN_MYANIMELIST_USERNAME: Amayacrab
          PLUGIN_MYANIMELIST_SECTIONS: statistics_simple, character_favorites, anime_favorites 
          PLUGIN_MYANIMELIST_ANIME_FAVORITES_MAX: 3
          PLUGIN_MYANIMELIST_CHARACTER_FAVORITES_MAX: 5
          PLUGIN_MYANIMELIST_CHARACTER_FAVORITES_TITLE: "Waifus"
          PLUGIN_MYANIMELIST_STATISTICS_SIMPLE_TITLE: "MAL Stats"
