name: WeebProfile
on:
  # 🦀 Schedule
  schedule: [{ cron: "0 12 * * *" }] # Everyday at 12:00 UTC

  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🦀 LastFM 🦀
        uses: LucasHenriqueDiniz/WeebProfile@main
        with:
          FILENAME: LastFM.svg
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          STORAGE_METHOD: gist
          SIZE: half

          PLUGIN_LASTFM: true
          PLUGIN_LASTFM_HIDE_HEADER: true
          PLUGIN_LASTFM_USERNAME: Amayacrab
          PLUGIN_LASTFM_STYLE: default
          PLUGIN_LASTFM_SECTIONS: recent_tracks, top_artists_default, top_albums_grid
          PLUGIN_LASTFM_RECENTTRACKS_MAX: 5
          PLUGIN_LASTFM_TOPARTISTS_MAX: 5
          PLUGIN_LASTFM_TOPALBUMS_MAX: 4

      - name: 🦀 MyAnimeList 🦀
        uses: LucasHenriqueDiniz/WeebProfile@main
        with:
          FILENAME: MyAnimeList.svg
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          STORAGE_METHOD: gist
          SIZE: half

          PLUGIN_MAL: true
          PLUGIN_LASTFM_HIDE_HEADER: true
          PLUGIN_MAL_HIDE_HEADER: true
          PLUGIN_MAL_USERNAME: Amayacrab
          PLUGIN_MAL_STYLE: default
          PLUGIN_MAL_SECTIONS: stats_simple, character_simple_favorites, anime_favorites
          PLUGIN_MAL_ANIME_FAVORITES_MAX: 3
          PLUGIN_MAL_CHARACTER_FAVORITES_MAX: 5
