name: WeebProfile
on:
  # 🦀 Schedule
  schedule: [{ cron: "0 0 * * *" }]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
jobs:
  weeb_profile:
    runs-on: ubuntu-latest
    steps:
      - name: 🦀 LastFM & Github 🦀
        uses: LucasHenriqueDiniz/WeebProfile@main
        with:
          FILENAME: LastFM.svg
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_TOKEN: ${{ secrets.WEEB_GH_TOKEN }}
          STORAGE_METHOD: gist
          STYLE: default
          SIZE: half

          PLUGIN_LASTFM: true
          PLUGIN_LASTFM_HIDE_HEADER: true
          PLUGIN_LASTFM_USERNAME: Amayacrab
          PLUGIN_LASTFM_SECTIONS: recent_tracks, top_artists_grid, top_albums_grid
          PLUGIN_LASTFM_RECENTTRACKS_MAX: 5
          PLUGIN_LASTFM_TOPARTISTS_MAX: 4
          PLUGIN_LASTFM_TOPALBUMS_MAX: 4

          PLUGIN_GITHUB: true
          PLUGIN_GITHUB_HIDE_HEADER: true
          PLUGIN_GITHUB_USERNAME: LucasHenriqueDiniz
          PLUGIN_GITHUB_SECTIONS: favorite_languages
          PLUGIN_GITHUB_FAVORITE_LANGUAGES_TITLE: "<qnt> Languages"

      - name: 🦀 MyAnimeList 🦀
        uses: LucasHenriqueDiniz/WeebProfile@main
        with:
          FILENAME: MyAnimeList.svg
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_TOKEN: ${{ secrets.WEEB_GH_TOKEN }}
          STORAGE_METHOD: gist
          SIZE: half
          STYLE: default

          PLUGIN_MAL: true
          PLUGIN_MAL_HIDE_HEADER: true
          PLUGIN_MAL_USERNAME: Amayacrab
          PLUGIN_MAL_SECTIONS: statistics_simple, anime_bar, character_simple_favorites, anime_favorites
          PLUGIN_MAL_ANIME_FAVORITES_MAX: 3
          PLUGIN_MAL_CHARACTER_FAVORITES_MAX: 5
          PLUGIN_MAL_CHARACTER_FAVORITES_TITLE: "Waifus"
          PLUGIN_MAL_STATISTICS_SIMPLE_TITLE: "MAL Stats"
