name: WeebProfile
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:

jobs:
  weeb_profile:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: 🦀 Github 🦀
        uses: LucasHenriqueDiniz/WeebProfile@main
        with:
          FILENAME: Github.svg
          GIST_ID: 8aacc3d1ccca110d8358e35517d8fe40
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          STORAGE_METHOD: gist
          
          PLUGIN_GITHUB: true
          PLUGIN_GITHUB_USERNAME: LucasHenriqueDiniz
          PLUGIN_GITHUB_SECTIONS: profile, favorite_languages, code_habits
          
      - name: 🦀 LastFM & MyAnimeList 🦀
        uses: LucasHenriqueDiniz/WeebProfile@main
        with:
          FILENAME: MyAnimeList.svg
          GIST_ID: 8aacc3d1ccca110d8358e35517d8fe40
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          STORAGE_METHOD: gist
          
          PLUGIN_LASTFM: true
          PLUGIN_LASTFM_USERNAME: Amayacrab
          PLUGIN_LASTFM_SECTIONS: recent_tracks
          PLUGIN_LASTFM_RECENT_TRACKS_MAX: 5
          
          PLUGIN_MYANIMELIST: true
          PLUGIN_MYANIMELIST_USERNAME: Amayacrab
          PLUGIN_MYANIMELIST_SECTIONS: character_simple_favorites, anime_favorites 
          PLUGIN_MYANIMELIST_ANIME_FAVORITES_MAX: 3
          PLUGIN_MYANIMELIST_CHARACTER_FAVORITES_MAX: 5
          PLUGIN_MYANIMELIST_CHARACTER_FAVORITES_TITLE: "Waifus"
